# Generated by Django 3.2.18 on 2023-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('staticIncome', models.FloatField()),
                ('status', models.IntegerField()),
                ('imgUrl', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Currency',
            },
        ),
    ]
